### ISSUE TITLE
Nested Documents

### ISSUE THREAD

**Issue by yahyatabba** [firebase/friendlyeats-ios#19]
Hello everyone,

You put (reviews as Collection) inside Restaurants Collections.

What different between this and reviews collection in the base path, and set rest_id and user_id inside it??

**Comment by samtstern** [comment]
@yahyatabba good question!  There's not much difference, just a different way of organizing the data.  We chose a subcollection mostly because we want this codelab to show off as many parts of Firestore as possible.

Here are a few small differences:

- If you wanted to query "ratings for restaurant X ordered by time" then you don't need a custom index when using a subcollection, but you do if you're using a root-level collection.
- It's sometimes easier to write good security rules when using subcollections since the path tells you about the expected data.
- If we ever need to analyze all reviews across all restaurants, we would *not* want to use subcollections.
